baseURL: https://blog.netify.my.id
languageCode: id-ID
defaultContentLanguage: id
title: My New Hugo Site
theme: "PaperModX"


# diambil dari PaperModX
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperModX]
    # author: Me
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2 January 2006"
    defaultTheme: auto # dark, light
    # disableThemeToggle: false
    EnableInstantClick: false
    EnableInstantPage: true
    
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    # label:
    #     text: "Home"
    #     icon: /apple-touch-icon.png
    #     iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        # title: ExampleSite
        # subtitle: "This is subtitle"
        # imageUrl: "<img location>"
        # imageWidth: 120
        # imageHeight: 120
        # imageTitle: my image
        # buttons:
        #     - name: Posts
        #       url: posts
        #     - name: Tags
        #       url: tags

    # home-info mode
    homeInfoParams:
      Title: "Hai \U0001F44B"
      Content: >-
        Selamat datang di blog remake dengan menggunakan Hugo, alasannya karena saya tidak bisa mengontrol nextjs.
        hehe.
        Untuk kode, masih hancur. Ya begitulah.

    socialIcons:
      - name: matrix
        url: "https://matrix.to/#/@testeraphy:beeper.com"
      - name: sharkey
        url: "https://shonk.social/@testeraphy"
      - name: github
        url: "https://github.com/intiplink"
      - name: rss
        url: "/index.xml"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: Kategori
      url: /categories/
      weight: 10
    - name: Arsip
      url: /arsip/
    - name: Cari
      url: /cari/

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Read: https://github.com/reorx/hugo-PaperModX/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai